# Generated by Django 3.2.5 on 2021-07-21 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrApp', '0002_auto_20210721_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instalacion',
            options={'ordering': ['fecha_instalacion'], 'verbose_name': 'Instalación', 'verbose_name_plural': 'Instalaciones'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero_cliente',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otros', 'Otros')], default=0, max_length=20, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='perfil_cliente',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Empleado', 'Empleado'), ('Socio', 'Socio')], default=0, max_length=20, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='barrio_inmueble',
            field=models.CharField(choices=[('Palmas', 'Palmas'), ('Mirador', 'Mirador')], default=0, max_length=20, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='ciudad_inmueble',
            field=models.CharField(choices=[('Giron', 'Girón'), ('Bucaramanga', 'Bucaramanga')], default=0, max_length=20, verbose_name='Ciudad'),
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('Instalación', 'Instalación'), ('Mantenimiento', 'Mantenimiento'), ('Retiro', 'Retiro'), ('PQR', 'PQR')], default=0, max_length=20, verbose_name='Tipo de solicitud')),
                ('fechaInicia_solicitud', models.DateField(auto_now=True, verbose_name='Fecha Inicial')),
                ('obsInicia_solicitud', models.TextField(verbose_name='Observación Inicia')),
                ('fechaFinal_solicitud', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
                ('obsFinal_solicitud', models.TextField(blank=True, null=True, verbose_name='Observación Final')),
                ('estado_solicitud', models.CharField(choices=[('Activo', 'Activo'), ('En proceso', 'En proceso'), ('Cerrado', 'Cerrado')], default=0, max_length=20, verbose_name='Estado de la solicitud')),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministrApp.cliente', verbose_name='Nombre cliente')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['estado_solicitud'],
            },
        ),
    ]
