# Generated by Django 3.2.5 on 2021-07-21 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrApp', '0003_auto_20210721_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministrApp.instalacion', verbose_name='Código Instalación'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_solicitud',
            field=models.CharField(blank=True, choices=[('Instalación', 'Instalación'), ('Mantenimiento', 'Mantenimiento'), ('Retiro', 'Retiro'), ('PQR', 'PQR')], default=0, max_length=20, null=True, verbose_name='Tipo de solicitud'),
        ),
    ]
