# Generated by Django 3.2.5 on 2021-07-22 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrApp', '0005_aporte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aporte',
            options={'ordering': ['id_cliente', 'valor_aporte'], 'verbose_name': 'Aporte', 'verbose_name_plural': 'Aportes'},
        ),
        migrations.AlterField(
            model_name='aporte',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministrApp.cliente', verbose_name='Nombre Socio'),
        ),
        migrations.CreateModel(
            name='gastoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gastoOperativo', models.DateField(verbose_name='Fecha')),
                ('concepto_gastoOperativo', models.CharField(choices=[('conbustible', 'conbustible'), ('Salario', 'Salario'), ('Arriendo', 'Arriendo')], default=0, max_length=20, verbose_name='Concepto')),
                ('obs_gastoOperativo', models.TextField(verbose_name='Observacion')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministrApp.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Gasto Operativo',
                'verbose_name_plural': 'Gastos Operativos',
                'ordering': ['id_cliente', 'concepto_gastoOperativo'],
            },
        ),
    ]
