# Generated by Django 3.2.5 on 2021-07-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrApp', '0009_auto_20210721_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pagoServicio', models.DateField(verbose_name='Fecha')),
                ('valor_pagoServicio', models.IntegerField(verbose_name='Valor Cancelado')),
                ('obs_pagoServicio', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('id_instalacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministrApp.instalacion', verbose_name='Instalación')),
            ],
            options={
                'verbose_name': 'Pago de Servicio',
                'verbose_name_plural': 'Pagos de Servicio',
                'ordering': ['fecha_pagoServicio'],
            },
        ),
    ]
