# Generated by Django 3.2.5 on 2021-07-22 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrApp', '0010_pagoservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_material', models.DateField(verbose_name='Fecha')),
                ('nombre_material', models.CharField(max_length=100, verbose_name='Nombre Material')),
                ('mac_material', models.CharField(max_length=100, verbose_name='MAC-Referencia')),
                ('userPass_material', models.CharField(blank=True, max_length=100, null=True, verbose_name='User / Pass')),
                ('obs_material', models.TextField(verbose_name='Observación')),
                ('estado_material', models.CharField(choices=[('Activo', 'Activo'), ('En proceso', 'En proceso'), ('Cerrado', 'Cerrado')], default=0, max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre_material'],
            },
        ),
        migrations.CreateModel(
            name='materialInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_materialInstalacion', models.DateField(verbose_name='Fecha')),
                ('obs_materialInstalacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('id_instalacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministrApp.instalacion', verbose_name='Instalación')),
                ('id_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdministrApp.material', verbose_name='Material')),
            ],
        ),
        migrations.AddField(
            model_name='instalacion',
            name='id_material',
            field=models.ManyToManyField(blank=True, through='AdministrApp.materialInstalacion', to='AdministrApp.material', verbose_name='Material'),
        ),
    ]
