# Generated by Django 3.2.5 on 2021-07-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrApp', '0011_auto_20210721_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialinstalacion',
            options={'ordering': ['id'], 'verbose_name': 'Material de Instalación', 'verbose_name_plural': 'Materiales de Instalación'},
        ),
    ]
